<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktív',
    'Command' => 'Parancs',
    'Create Cron Job' => 'Cron feladat létrehozása',
    'Cron Job Runs' => 'Cron feladat futások',
    'Cron Jobs' => 'Cron feladatok',
    'Error Output' => 'Hiba kimenet',
    'Exit Code' => 'Kimeneti kód',
    'Finish' => 'Befejezés',
    'ID' => 'ID',
    'In Progress' => 'Folyamatban',
    'Job' => 'Feladat',
    'Last' => 'Utolsó',
    'Logs' => 'Logok',
    'Name' => 'Név',
    'Output' => 'Kimenet',
    'Pid' => 'PID',
    'Reset' => 'Visszaállítás',
    'Runtime' => 'Futási idő',
    'Save' => 'Mentés',
    'Schedule' => 'Ütemterv',
    'Start' => 'Kezdés',
    'Success' => 'Sikeres',
    'The requested page does not exist.' => 'A keresett oldal nem létezik',
    'Update' => 'Módosítás',
    'Update Cron Job: {nameAttribute}' => 'Cron feledat módosítása: {nameAttribute}',
    'Are you sure to delete this item?' => '@@Biztos törlöd ezt a tételt?@@',
];
