<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Active',
    'Command' => 'Command',
    'Create Cron Job' => 'Create cron job',
    'Cron Job Runs' => 'Cron job runs',
    'Cron Jobs' => 'Cron jobs',
    'Error Output' => 'Error output',
    'Exit Code' => 'Exit code',
    'Finish' => 'Finish',
    'ID' => 'ID',
    'In Progress' => 'In progress',
    'Job' => 'Job',
    'Last' => 'Last',
    'Logs' => 'Logs',
    'Name' => 'Name',
    'Output' => 'Output',
    'Pid' => 'Pid',
    'Reset' => 'Reset',
    'Runtime' => 'Runtime',
    'Save' => 'Save',
    'Schedule' => 'Schedule',
    'Start' => 'Start',
    'Success' => 'Success',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Update' => 'Update',
    'Update Cron Job: {nameAttribute}' => 'Update cron job: {nameAttribute}',
    'Are you sure to delete this item?' => '@@Are you sure to delete this item?@@',
];
